In [48]:
import numpy as np

arr = np.array([1,2,3])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.dtype)

floatArr = np.array([1.001,1.002,1.003])
print(floatArr)
print(floatArr.dtype)
print(type(floatArr[0]))

strArr = np.array(['hello','world'])
print(strArr)
print(strArr.dtype)
print(type(strArr[0]))

[1 2 3]
1
(3,)
int32
[1.001 1.002 1.003]
float64
<class 'numpy.float64'>
['hello' 'world']
<U5
<class 'numpy.str_'>


In [30]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)
print(arr_2d.ndim)
print(arr_2d.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


In [35]:
arr_3d = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
print(arr_3d)
print(arr_3d.ndim)
print(arr_3d.shape)

arr_3d[0][1][2]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
3
(3, 3, 3)


6